Scriptable Perks Implemented (Pistol Broken)
SerializedObjectNotCreatableException: Object at index 0 is null
UnityEditor.Editor.CreateSerializedObject () (at <2348e9bf86984d808478203ec94ae526>:0)
UnityEditor.Editor.GetSerializedObjectInternal () (at <2348e9bf86984d808478203ec94ae526>:0)
UnityEditor.Editor.get_serializedObject () (at <2348e9bf86984d808478203ec94ae526>:0)
UnityEditor.GameObjectInspector.OnEnable () (at <2348e9bf86984d808478203ec94ae526>:0)

im not entirely sure whats going on but now bullets jsut bounce off walls